includes_/head.html
<meta name="google-site-verification" content="Sgpxtv-gcnZfd3AFF5pyTsYo7FxbS_31V1CWyEkclfc" />
<header>
  <nav>
    <ul style="list-style:none; display:flex; gap:20px; padding:10px; background:#333;">
      <li><a href="{{ '/' | relative_url }}" style="color:white; text-decoration:none;">Home</a></li>
      <li><a href="{{ '/about' | relative_url }}" style="color:white; text-decoration:none;">About</a></li>
      <li><a href="{{ '/publications' | relative_url }}" style="color:white; text-decoration:none;">Publications</a></li>
      <li><a href="{{ '/contact' | relative_url }}" style="color:white; text-decoration:none;">Contact</a></li>
    </ul>
  </nav>
</header>

title: "Dr. Menka | Resume"
description: "Assistant Professor & Head, Department of Botany, M.J.K. College, Bettiah"
author: "Dr. Menka"

theme: jekyll-theme-cayman

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

