title: "Dr. Menka | Resume"
description: "Assistant Professor & Head, Department of Botany, M.J.K. College, Bettiah"
author: "Dr. Menka"

theme: jekyll-theme-cayman

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

